[package]
name = "york"
version = "0.1.0"
authors = ["york"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = { git = "https://github.com/crossterm-rs/crossterm.git" }
